### ISSUE TITLE
Package function: trie_contain()

### ISSUE THREAD

**Issue by rainbowxyt0305** [UBC-MDS/reasytries#11]

**Comment by shoebillm** [comment]
- `trie_contain` function takes in a `trie` class and a `word` string to be searched 
- the function transfers the `word` to a character list containing every letter inside 
- the function then loops through the character list to check if every letter is contained in the `trie` structure
- the function then checks if the last letter in the `word` stored in `trie` is labelled with `is_complete_word == TRUE` 

**Exception handling**
- `trie_contain` function checks if the first input `trie` is an instance of a trie class (if not, it will throw an error to warn the user the correct type)
- `trie_contain` function checks if the  second input `word` is an string containing only letters (if not, it will throw an error to warn the user the correct input format)

**Comment by shoebillm** [comment]
**Test functions**
- test if the function returns `FALSE` when searching through an empty trie
- test if the function returns `FALSE` when the word does not exist in the trie
- test if the function returns `FALSE` when all letters of the word exist but they are not stored as a complete word in the trie
- test if the function returns `TRUE` when the word exists in the trie as a complete word

**Exception handling**
- test if the function throws an error when the input trie is not a class trie or the input word is not a string
- test if the function throws an error when the input word contains symbols or numbers other than letters
