### ISSUE TITLE
Package function: trie_delete()

### ISSUE THREAD

**Issue by rainbowxyt0305** [UBC-MDS/reasytries#13]

**Comment by Andrew-Tan** [comment]
- `trie_delete` function takes in a `trie` class and a `word_to_delete` string to be deleted from the trie
- The function traverses down the trie to find out if `word_to_delete` exists in the trie. If exists, it will remove the word.
- If the word does not exist in the trie, the function will report deletion failure and leave the trie as it is.

**Exception handling**
- Checks if the first input `trie` is an instance of a trie class
  - If not, an error will be thrown with an error message
- Checks if the  second input `word_to_delete` is a non-empty string
  - If not, an error will be thrown with an error message

**Comment by Andrew-Tan** [comment]
Test plan:
- Test if an error will be thrown if supplied a non-trie class to the first argument
- Test if an error will be thrown if supplied a non-string or empty string to the second argument.
- Test if the function will leave the trie as it is if trying to delete a non-existing word
- Test if the function will correctly delete the specified words
