### ISSUE TITLE
3. Initiate a package review request (Python)

### ISSUE THREAD

**Issue by rainbowxyt0305** [UBC-MDS/reasytries#26]

**Comment by shoebillm** [comment]
* Explain how the and why the package falls under these categories (briefly, 1-2 sentences):

> The `pyeasytries` can store any words passed by the user for facilitating later searching. "Trie" is an infix of the word "retrieving".

* Who is the target audience and what are scientific applications of this package?

> The target audience is the users who would like to quickly access pre-stored words by full spelling or prefix. The scientific applications of this package can be in predictive text and autocomplete dictionary (potentially spell checking).

* Are there other Python packages that accomplish the same thing? If so, how does yours differ?

> There is a similar Python package named `pygtrie`, which contains `Trie`, `CharTrie` and `StringTrie` classes and multiple functions. Compared to `pygtrie`, the `pyeasytrie` package is more user-friendly as it does not require the user to have too much programming background knowledge to create the tries or search through the tries.
